[tool.black]
line-length = 100
target-version = ['py39']
exclude = 'generated'

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "aioazuredevops",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true


[tool.pytest.ini_options]
testpaths = [
    "tests",
]
norecursedirs = [
    ".git",
]

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "abstract-class-little-used",
    "abstract-method",
    "consider-using-assignment-expr",
    "consider-using-f-string",
    "consider-using-namedtuple-or-dataclass",
    "cyclic-import",
    "duplicate-code",
    "format",
    "inconsistent-return-statements",
    "invalid-name",
    "locally-disabled",
    "no-name-in-module",
    "not-context-manager",
    "redefined-builtin",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-boolean-expressions",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "unused-argument",
    "wrong-import-order",
]
